# Generated by Django 3.2.5 on 2021-09-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=30)),
                ('author_name', models.CharField(max_length=30)),
                ('quantity', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('book_categories', models.CharField(max_length=30)),
            ],
        ),
    ]
